- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformTsfmcMopp
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesMopp
    neck: ClothingNeckIFFGreen
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsMagAdv
    id: CBURNPDA
    pocket1: RadioHandheldNF # Frontier: RadioHandheld<RadioHandheldNF
    pocket2: WeaponLaserPistolNF # Frontier: WeaponLaserGun<WeaponLaserPistolNF
    belt: ClothingBeltWebbingsBigRangerGreen
    suitStorage: PortableRecharger
  inhand:
  - PortableRecharger
  storage:
    back:
    - WeaponShotgunDoubleBarreled
    - GrenadeFlashBang
    - MedkitCombatFilled
    - MedkitCombatFilled
    - ShipVoucherFrontierGuard
    - GrenadeIncendiaryNfsd
    - WeaponEnergyShotgun
    - SyringeCaseAltFilled
    - PillMesotaxinide
    - PillMesotaxinide
    - Handcuffs
    - Handcuffs
    - TrackingImplanter
    - MedicalTrackingImplanterLabeled
    belt:
    - AmmoBox12_gaugeIncendiary
    - AmmoBox12_gaugeIncendiary
    - SyndicateJawsOfLife
    - PowerDrill
    - WelderExperimental
    - BluespaceLifelineImplanter
    - RadioImplanterCentcomm
    - HandHeldMassScannerBorg